#!/usr/bin/perl -w
use strict;
##########################################################################
# $Id: onlyhost,v 1.4 2004/06/21 14:18:57 kirk Exp $
##########################################################################

# This feature concieved by mark@winksmith.com

my $hostname = $ENV{'LOGWATCH_ONLY_HOSTNAME'};

if (($ENV{'LOGWATCH_DEBUG'} > 5) and $hostname) {
   print STDERR "DEBUG: Inside OnlyHostname for $hostname\n";
}

#If called from a service config file it passes the param as an ARG
if ($#ARGV == 0) {      #put in or override the host id
        $hostname = $ARGV[0];
}

my $line;
while (defined($line = <STDIN>)) {
   if ($hostname) {
      if ($line =~ m/^... .. ..:..:.. $hostname\b/io) {
         print $line;
      }
   } else {
      print $line;
   }
}

