#!/usr/bin/perl -w
##########################################################################
# $Id: removeheaders,v 1.3 2002/10/12 02:08:17 kirk Exp $
##########################################################################

########################################################
# This was written and is maintained by:
#    Kirk Bauer <kirk@kaybee.org>
#
# Please send all comments, suggestions, bug reports,
#    etc, to kirk@kaybee.org.
########################################################

while (defined($ThisLine = <STDIN>)) {
    $ThisLine =~ s/^... ... .. ..:..:.. .... [0123456789]+ //;
    print $ThisLine;
}

